"""Update hairstyle model

Revision ID: e1e91a527c31
Revises: 54c285f2f8a8
Create Date: 2024-09-30 21:31:03.455609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e91a527c31'
down_revision = '54c285f2f8a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hairstyles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hairstyles', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
